using System;

namespace PokemonPacketCorruptor
{
    internal static class CharacterHelper
    {
        internal static byte ToPokemonChar(char c)
        {
            return (byte)(c + 63);
        }

        internal static char ToChar(byte c)
        {
            if (c == 0x50 || c == 0x00) return '\0';

            return (char)((char)c - 63);
        }
    }

    public enum Action : byte
    {
        Attack1 = 0x60,
        Attack2 = 0x61,
        Attack3 = 0x62,
        Attack4 = 0x63,
        Switch1 = 0x64,
        Switch2 = 0x65,
        Switch3 = 0x66,
        Switch4 = 0x67
    }

    [Flags]
    public enum PokemonStatus : byte
    {
        Normal = 0x00,
        Asleep = 0x04,
        Poisonned = 0x08,
        Burned = 0x10,
        Frozen = 0x20,
        Paralyzed = 0x40
    }

    public enum PokemonType : byte
    {
        Normal = 0x00,
        Fighting = 0x01,
        Flying = 0x02,
        Poison = 0x03,
        Ground = 0x04,
        Rock = 0x05,
        Bug = 0x07,
        Ghost = 0x08,
        Fire = 0x14,
        Water = 0x15,
        Grass = 0x16,
        Electric = 0x17,
        Psychic = 0x18,
        Ice = 0x19,
        Dragon = 0x1A
    }

    public enum PokemonAttack : byte
    {
        None = 0x00,
        Pound = 0x01,
        KarateChop = 0x02,
        DoubleSlap = 0x03,
        CometPunch = 0x04,
        MegaPunch = 0x05,
        PayDay = 0x06,
        FirePunch = 0x07,
        IcePunch = 0x08,
        ThunderPunch = 0x09,
        Scratch = 0x0A,
        ViceGrip = 0x0B,
        Guillotine = 0x0C,
        RazorWind = 0x0D,
        SwordsDance = 0x0E,
        Cut = 0x0F,
        Gust = 0x10,
        WingAttack = 0x11,
        Whirlwind = 0x12,
        Fly = 0x13,
        Bind = 0x14,
        Slam = 0x15,
        VineSwip = 0x16,
        Stomp = 0x17,
        DoubleKick = 0x18,
        MegaKick = 0x19,
        JumpKick = 0x1A,
        RollingKick = 0x1B,
        SandAttack = 0x1C,
        Headbutt = 0x1D,
        HornAttack = 0x1E,
        FuryAttack = 0x1F,
        HornDrill = 0x20,
        Tackle = 0x21,
        BodySlam = 0x22,
        Wrap = 0x23,
        TakeDown = 0x24,
        Thrash = 0x25,
        DoubleEdge = 0x26,
        TailWhip = 0x27,
        PoisonSting = 0x28,
        Twineedle = 0x29,
        PinMissile = 0x2A,
        Leer = 0x2B,
        Bite = 0x2C,
        Growl = 0x2D,
        Roar = 0x2E,
        Sing = 0x2F,
        Supersonic = 0x30,
        SonicBoom = 0x31,
        Disable = 0x32,
        Acid = 0x33,
        Ember = 0x34,
        Flamethrower = 0x35,
        Mist = 0x36,
        WaterGun = 0x37,
        HydroPump = 0x38,
        Surf = 0x39,
        IceBeam = 0x3A,
        Blizzard = 0x3B,
        Psybeam = 0x3C,
        BubbleBeam = 0x3D,
        AuroraBeam = 0x3E,
        HyperBeam = 0x3F,
        Peck = 0x40,
        DrillPeck = 0x41,
        Submission = 0x42,
        LowKick = 0x43,
        Counter = 0x44,
        SeismicToss = 0x45,
        Strength = 0x46,
        Absorb = 0x47,
        MegaDrain = 0x48,
        LeechSeed = 0x49,
        Growth = 0x4A,
        RazorLeaf = 0x4B,
        SolarBeam = 0x4C,
        PoisonPower = 0x4D,
        StunSpore = 0x4E,
        SleepPowder = 0x4F,
        PetalDance = 0x50,
        StringShot = 0x51,
        DragonRage = 0x52,
        FireSpin = 0x53,
        ThunderShock = 0x54,
        Thunderbolt = 0x55,
        ThunderWave = 0x56,
        Thunder = 0x57,
        RockThrow = 0x58,
        Earthquake = 0x59,
        Fissure = 0x5A,
        Dig = 0x5B,
        Toxic = 0x5C,
        Confusion = 0x5D,
        Psychic = 0x5E,
        Hypnosis = 0x5F,
        Meditate = 0x60,
        Agility = 0x61,
        QuickAttack = 0x62,
        Rage = 0x63,
        Teleport = 0x64,
        NightShade = 0x65,
        Mimic = 0x66,
        Screech = 0x67,
        DoubleTeam = 0x68,
        Recover = 0x69,
        Harden = 0x6A,
        Minimize = 0x6B,
        SmokeScreen = 0x6C,
        ConfuseRay = 0x6D,
        Withdraw = 0x6E,
        DefenseCurl = 0x6F,
        Barrier = 0x70,
        LightScreen = 0x71,
        Haze = 0x72,
        Reflect = 0x73,
        FocusEnergy = 0x74,
        Bide = 0x75,
        Metronome = 0x76,
        MirrorMove = 0x77,
        Selfdestruct = 0x78,
        EggBomb = 0x79,
        Lick = 0x7A,
        Smog = 0x7B,
        Sludge = 0x7C,
        BoneClub = 0x7D,
        FireBlast = 0x7E,
        Waterfall = 0x7F,
        Clamp = 0x80,
        Swift = 0x81,
        SkullBash = 0x82,
        SpikeCannon = 0x83,
        Constrict = 0x84,
        Amnesia = 0x85,
        Kinesis = 0x86,
        Softboiled = 0x87,
        HiJumpKick = 0x88,
        Glare = 0x89,
        DreamEater = 0x8A,
        PoisonGas = 0x8B,
        Barrage = 0x8C,
        LeechLife = 0x8D,
        LovelyKiss = 0x8E,
        SkyAttack = 0x8F,
        Transform = 0x90,
        Bubble = 0x91,
        DizzyPunch = 0x92,
        Spore = 0x93,
        Flash = 0x94,
        PsyWave = 0x95,
        Splash = 0x96,
        AcidArmor = 0x97,
        Crabhammer = 0x98,
        Explosion = 0x99,
        FurySwipes = 0x9A,
        Bonemerang = 0x9B,
        Rest = 0x9C,
        RockSlide = 0x9D,
        HyperFang = 0x9E,
        Sharpen = 0x9F,
        Conversion = 0xA0,
        TriAttack = 0xA1,
        SuperFang = 0xA2,
        Slash = 0xA3,
        Substitude = 0xA4,
        Struggle = 0xA5, // End Of Gen1
    }
}